[project]
name = "amazon"
version = "0.1.0"
description = "Amazon Product Search MCP Server with AI-powered recommendations"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mcp[cli]>=1.9.4",
    "fastapi>=0.104.0",
    "uvicorn>=0.24.0",
    "httpx>=0.25.0",
]
